// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpdrjoqpsynbuqjdazst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwZHJqb3Fwc3luYnVxamRhenN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTIwOTIsImV4cCI6MjA2MDU2ODA5Mn0.--OkDKbGbQiBpGR4K_A_3gY6aHODel8CjSMcKP2fBcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);